name: Gh-pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Flutter Action
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.3"

      - name: Create env.json file
        run: |
          cat > env.json << 'EOF'
          {
            "DEBUG_API_URL": "http://localhost:3000",
            "PRODUCTION_API_URL": "https://finfx-backend-917312759089.asia-south2.run.app"
          }
          EOF

      - name: Deploy to GitHub Pages
        uses: bluefireteam/flutter-gh-pages@v9
        with:
          compileToWasm: true
          customArgs: --dart-define-from-file=env.json
